all:
	arm-linux-gcc *.c -lpthread -I /root/project/arm_sqlite3/include/ -I /root/project/arm_jpeg/include/ -L /root/project/arm_sqlite3/lib -lsqlite3 -L /root/project/arm_jpeg/lib/ -ljpeg
clean:
		rm -rf camera1 
		rm -rf /source/rootfs/rootfs/camera1 


